import type { Locale } from './usePrivacy'

const copy = {
  ru: {
    title: 'Белый список', description: 'Люди и автомобили, включённые в список исключений.',
    addPerson: 'Добавить человека', addVehicle: 'Добавить автомобиль', entryTypes: 'Тип записей',
    people: 'Люди', vehicles: 'Автомобили', useList: 'Использовать список', search: 'Поиск по имени или номеру',
    onlyEnabled: 'Только активные', refresh: 'Обновить', downloadCsv: 'Скачать CSV', photoCount: 'Количество фотографий', yes: 'Да', no: 'Нет', active: 'Активна', name: 'Имя', vehicle: 'Автомобиль',
    photos: 'Фотографии', plate: 'Номер', added: 'Добавлено', actions: 'Действия', edit: 'Изменить', remove: 'Удалить',
    loading: 'Загрузка списка…', noMatches: 'Записи не найдены', noPeople: 'В списке пока нет людей',
    noVehicles: 'В списке пока нет автомобилей', entries: 'Записей:', listDisabled: 'Список выключен',
    deleteTitle: 'Удалить запись?', deletePerson: 'Запись и её фотографии будут удалены.',
    deleteVehicle: 'Автомобиль будет удалён из списка.', cancel: 'Отмена', deleting: 'Удаление…',
    editTitle: 'Изменить запись', close: 'Закрыть', label: 'Название', personPlaceholder: 'Имя и фамилия',
    vehiclePlaceholder: 'Владелец или название автомобиля', registration: 'Регистрационный номер', country: 'Страна',
    kazakhstan: 'Казахстан', russia: 'Россия', otherCountry: 'Другая', addPhotos: 'Добавить фотографии',
    replacePhotos: 'Заменить фотографии', pickPhotos: 'Выбрать фотографии', photoFormats: 'JPEG, PNG, WebP · до 10 МБ',
    notes: 'Примечание', entryEnabled: 'Запись активна', saving: 'Сохранение…', save: 'Сохранить',
    requirePhoto: 'Выберите хотя бы одну фотографию.', imageTypes: 'Допустимы фотографии JPEG, PNG и WebP.',
    imageSize: 'Размер одной фотографии — до 10 МБ.',
    photoLimit: (maximum: number) => `Можно добавить не более ${maximum} ${maximum === 1 ? 'фотографии' : 'фотографий'}.`,
    activeLabel: (label: string) => `Активна: ${label}`,
    editLabel: (label: string) => `Изменить: ${label}`,
    removeLabel: (label: string) => `Удалить: ${label}`,
    tablePhotoAlt: (label: string, index: number) => `${label}, фото ${index}`,
    photoAlt: (index: number, label: string) => `Фотография ${index}: ${label}`,
    selectedPhotoAlt: (index: number) => `Выбранная фотография ${index}`,
    removePhotoLabel: (index: number) => `Удалить фотографию ${index}`,
  },
  kk: {
    title: 'Ақ тізім', description: 'Ерекшеліктер тізіміне енгізілген адамдар мен көліктер.',
    addPerson: 'Адамды қосу', addVehicle: 'Көлікті қосу', entryTypes: 'Жазба түрлері',
    people: 'Адамдар', vehicles: 'Көліктер', useList: 'Тізімді қолдану', search: 'Аты немесе нөмірі бойынша іздеу',
    onlyEnabled: 'Тек белсенділер', refresh: 'Жаңарту', downloadCsv: 'CSV жүктеп алу', photoCount: 'Фотосуреттер саны', yes: 'Иә', no: 'Жоқ', active: 'Белсенді', name: 'Аты', vehicle: 'Көлік',
    photos: 'Фотосуреттер', plate: 'Нөмір', added: 'Қосылған күні', actions: 'Әрекеттер', edit: 'Өзгерту', remove: 'Жою',
    loading: 'Тізім жүктелуде…', noMatches: 'Жазбалар табылмады', noPeople: 'Тізімде әзірге адамдар жоқ',
    noVehicles: 'Тізімде әзірге көліктер жоқ', entries: 'Жазбалар:', listDisabled: 'Тізім өшірулі',
    deleteTitle: 'Жазбаны жою керек пе?', deletePerson: 'Жазба мен оның фотосуреттері жойылады.',
    deleteVehicle: 'Көлік тізімнен жойылады.', cancel: 'Болдырмау', deleting: 'Жойылуда…',
    editTitle: 'Жазбаны өзгерту', close: 'Жабу', label: 'Атауы', personPlaceholder: 'Аты мен тегі',
    vehiclePlaceholder: 'Иесі немесе көліктің атауы', registration: 'Тіркеу нөмірі', country: 'Ел',
    kazakhstan: 'Қазақстан', russia: 'Ресей', otherCountry: 'Басқа', addPhotos: 'Фотосуреттерді қосу',
    replacePhotos: 'Фотосуреттерді ауыстыру', pickPhotos: 'Фотосуреттерді таңдау', photoFormats: 'JPEG, PNG, WebP · 10 МБ-қа дейін',
    notes: 'Ескерту', entryEnabled: 'Жазба белсенді', saving: 'Сақталуда…', save: 'Сақтау',
    requirePhoto: 'Кемінде бір фотосуретті таңдаңыз.', imageTypes: 'JPEG, PNG және WebP фотосуреттерін қолдануға болады.',
    imageSize: 'Бір фотосуреттің өлшемі — 10 МБ-қа дейін.',
    photoLimit: (maximum: number) => `${maximum} фотосуреттен артық қосуға болмайды.`,
    activeLabel: (label: string) => `Белсенді: ${label}`,
    editLabel: (label: string) => `Өзгерту: ${label}`,
    removeLabel: (label: string) => `Жою: ${label}`,
    tablePhotoAlt: (label: string, index: number) => `${label}, ${index}-фотосурет`,
    photoAlt: (index: number, label: string) => `${index}-фотосурет: ${label}`,
    selectedPhotoAlt: (index: number) => `Таңдалған ${index}-фотосурет`,
    removePhotoLabel: (index: number) => `${index}-фотосуретті жою`,
  },
  en: {
    title: 'Whitelist', description: 'People and vehicles included in the exception list.',
    addPerson: 'Add person', addVehicle: 'Add vehicle', entryTypes: 'Entry types',
    people: 'People', vehicles: 'Vehicles', useList: 'Use list', search: 'Search by name or license plate',
    onlyEnabled: 'Active only', refresh: 'Refresh', downloadCsv: 'Download CSV', photoCount: 'Photo count', yes: 'Yes', no: 'No', active: 'Active', name: 'Name', vehicle: 'Vehicle',
    photos: 'Photos', plate: 'License plate', added: 'Added', actions: 'Actions', edit: 'Edit', remove: 'Delete',
    loading: 'Loading list…', noMatches: 'No matching entries', noPeople: 'No people in the list yet',
    noVehicles: 'No vehicles in the list yet', entries: 'Entries:', listDisabled: 'List disabled',
    deleteTitle: 'Delete entry?', deletePerson: 'The entry and its photos will be deleted.',
    deleteVehicle: 'The vehicle will be removed from the list.', cancel: 'Cancel', deleting: 'Deleting…',
    editTitle: 'Edit entry', close: 'Close', label: 'Name', personPlaceholder: 'First and last name',
    vehiclePlaceholder: 'Owner or vehicle name', registration: 'Registration number', country: 'Country',
    kazakhstan: 'Kazakhstan', russia: 'Russia', otherCountry: 'Other', addPhotos: 'Add photos',
    replacePhotos: 'Replace photos', pickPhotos: 'Select photos', photoFormats: 'JPEG, PNG, WebP · up to 10 MB',
    notes: 'Notes', entryEnabled: 'Entry active', saving: 'Saving…', save: 'Save',
    requirePhoto: 'Select at least one photo.', imageTypes: 'JPEG, PNG and WebP photos are supported.',
    imageSize: 'Each photo must be no larger than 10 MB.',
    photoLimit: (maximum: number) => `You can add no more than ${maximum} ${maximum === 1 ? 'photo' : 'photos'}.`,
    activeLabel: (label: string) => `Active: ${label}`,
    editLabel: (label: string) => `Edit: ${label}`,
    removeLabel: (label: string) => `Delete: ${label}`,
    tablePhotoAlt: (label: string, index: number) => `${label}, photo ${index}`,
    photoAlt: (index: number, label: string) => `Photo ${index}: ${label}`,
    selectedPhotoAlt: (index: number) => `Selected photo ${index}`,
    removePhotoLabel: (index: number) => `Delete photo ${index}`,
  },
} satisfies Record<Locale, Record<string, string | ((...args: never[]) => string)>>

export function useWhitelistCopy() {
  const { locale } = useLocale()
  return computed(() => copy[locale.value])
}
